# Generated by Django 5.2.17 on 2026-08-07 05:23

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField(default=datetime.date.today)),
                ('vehiculo', models.CharField(choices=[('TURBO', 'Turbo'), ('CAMION', 'Camión')], max_length=10)),
                ('estado', models.CharField(choices=[('RECOLECCION', 'En recolección'), ('TRANSITO', 'En tránsito'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECOLECCION', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calidad', models.CharField(choices=[('1RA', 'Primera'), ('2DA', 'Segunda')], max_length=3)),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField(default=datetime.date.today)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='PuntoRecoleccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField()),
                ('tipo_servicio', models.CharField(choices=[('COMPRA', 'Compra de mercancía'), ('FLETE', 'Servicio de flete')], max_length=10)),
                ('precio_flete_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='core.viaje')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('viaje', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='LoteCarga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calidad', models.CharField(choices=[('1RA', 'Primera'), ('2DA', 'Segunda')], max_length=3)),
                ('num_canastillas', models.PositiveSmallIntegerField()),
                ('peso_recoleccion_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_compra_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('punto_recoleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.puntorecoleccion')),
            ],
        ),
    ]
