# Generated by Django 5.2.17 on 2026-08-08 16:16

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_viaje_preciocliente_puntorecoleccion_lotecarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField(default=datetime.date.today)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntrega',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kg_primera_recibida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('kg_segunda_recibida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('precio_primera_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_segunda_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.entrega')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('pdf_url', models.CharField(blank=True, max_length=500)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='core.entrega')),
            ],
        ),
    ]
