# Generated by Django 5.2.17 on 2026-08-08 16:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entrega_detalleentrega_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleentrega',
            name='precio_primera_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleentrega',
            name='precio_segunda_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
