# Generated by Django 5.2.17 on 2026-08-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_detalleentrega_precio_primera_kg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaje',
            options={'ordering': ['-fecha_salida', '-creado_en']},
        ),
    ]
