# Generated by Django 5.2.17 on 2026-08-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_viaje_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre']},
        ),
    ]
