# Generated by Django 5.2.17 on 2026-08-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_options_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha_emision', '-creado_en']},
        ),
    ]
