# Generated by Django 5.2.17 on 2026-08-31 15:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_options_alter_factura_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margen_compra_kg_defecto', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Margen de ganancia por kg que se precarga en entregas de paradas tipo COMPRA.', max_digits=8)),
            ],
            options={
                'verbose_name': 'Configuración general',
                'verbose_name_plural': 'Configuración general',
            },
        ),
        migrations.AddField(
            model_name='detalleentrega',
            name='margen_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='detalleentrega',
            name='punto_recoleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_entrega', to='core.puntorecoleccion'),
        ),
    ]
