# Generated by Django 5.2.17 on 2026-09-02 17:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracion_detalleentrega_margen_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='margen_compra_kg_defecto',
        ),
        migrations.RemoveField(
            model_name='puntorecoleccion',
            name='precio_flete_kg',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='margen_flete_kg_defecto',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Margen por kg que se precarga en entregas de paradas tipo FLETE — la ganancia del transportador, calculada al momento de entregar.', max_digits=8),
        ),
    ]
