# Generated by Django 5.2.17 on 2026-09-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_configuracion_margen_compra_kg_defecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntorecoleccion',
            name='margen_flete_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Margen acordado por kg cuando el tipo es FLETE. Si queda vacío, se usa el valor por defecto de Configuración al momento de entregar.', max_digits=8, null=True),
        ),
    ]
