# Generated by Django 5.2.17 on 2026-09-09 19:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_puntorecoleccion_margen_flete_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionProveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_liquidacion', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedor')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='core.viaje')),
            ],
            options={
                'ordering': ['-fecha_emision', '-creado_en'],
                'unique_together': {('viaje', 'proveedor')},
            },
        ),
    ]
