# Generated by Django 5.2.17 on 2026-09-10 19:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_liquidacionproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='nombre_negocio',
            field=models.CharField(blank=True, default='FrutraQ', max_length=150),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='margen_flete_kg_defecto',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Margen por kg que se precarga en entregas de paradas tipo FLETE.', max_digits=8),
        ),
    ]
